version: '3.7'

services:

   naming-server:
      image: helenma33/mmv2-naming-server:0.0.1-SNAPSHOT
      deploy:
        resources:
          limits:
            memory: 700m
      ports:
        - "8761:8761"
      networks:
        - limits-network

   limits-service:
    image: helenma33/mmv2-limits-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8080:8080"
    networks:
      - limits-network
    restart : on-failure
    depends_on:
      - spring-cloud-config-server
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka


   spring-cloud-config-server:
    image: helenma33/mmv2-spring-cloud-config-server:0.0.1-SNAPSHOT
    deploy:
      resources:
       limits:
        memory: 700m
    ports:
      - "8888:8888"
    networks:
      - limits-network
    depends_on:
      - naming-server
    restart: on-failure
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

networks:
  limits-network: